# Generated by Django 6.0 on 2026-01-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشيخ')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن الشيخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scholars/', verbose_name='صورة الشيخ')),
            ],
            options={
                'verbose_name': 'شيخ',
                'verbose_name_plural': 'شيوخ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('investigator', models.CharField(blank=True, max_length=200, null=True, verbose_name='المحقق')),
                ('pdf_file', models.FileField(upload_to='books/', verbose_name='ملف PDF')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='school.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'كتب',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.scholar', verbose_name='الشيخ المحاضر')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
    ]
