# Generated by Django 6.0 on 2026-01-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='صورة الفرع')),
                ('bio', models.TextField(verbose_name='نبذة تعريفية')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'فروع',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='school.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholars', to='school.branch', verbose_name='الفرع'),
        ),
    ]
