# Generated by Django 6.0 on 2026-01-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_branch_lesson_branch_scholar_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عن مدرسة الغمارية لإحياء العلوم', max_length=200, verbose_name='العنوان الرئيسي')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('objectives', models.TextField(help_text='اكتب كل هدف في سطر منفصل', verbose_name='الأهداف (سطر لكل هدف)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='شعار المدرسة')),
            ],
            options={
                'verbose_name': 'صفحة عن المدرسة',
                'verbose_name_plural': 'صفحة عن المدرسة',
            },
        ),
    ]
