# Generated by Django 6.0 on 2026-01-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='ظ…ط¤ظ„ظپ ط؛ظٹط± ظ…ط¹ط±ظˆظپ', max_length=200, verbose_name='المؤلف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='ظˆطµظپ ط؛ظٹط± ظ…طھظˆظپط± ط\xadط§ظ„ظٹط§ظ‹'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='ظˆطµظپ ط§ظ„ظƒطھط§ط¨', verbose_name='وصف الكتاب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='books/', verbose_name='ملف الكتاب (PDF)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.category', verbose_name='التصنيف'),
        ),
    ]
