# Generated by Django 6.0 on 2026-01-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='مؤلف غير معروف', max_length=200, verbose_name='المؤلف'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='لا يوجد وصف', verbose_name='وصف الكتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='books/', verbose_name='ملف الكتاب (PDF)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.category', verbose_name='التصنيف'),
        ),
    ]
